App Monitoring for VM CPU added - Remove email after example deployment done

diff --git a/.github/workflows/terraform-cicd-pipeline.yml b/.github/workflows/terraform-cicd-pipeline.yml
--- a/.github/workflows/terraform-cicd-pipeline.yml
+++ b/.github/workflows/terraform-cicd-pipeline.yml
@@ -295,7 +295,7 @@ jobs:
               --resource-group rg-nodeapp-prod-ne \
               --query "defaultHostName" -o tsv)
             
-            curl -f -s -o /dev/null https://$APP_URL/health || echo "⚠️ App Service health check failed"
+            curl -f -s -o /dev/null https://$APP_URL/health || echo " App Service health check failed"
             echo "App Service is running"
           else
             echo "App Service is not running as expected"
